# Generated by Django 3.2.7 on 2022-07-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='aricle_image',
            field=models.ImageField(blank=True, default='article_images/default.jpg', null=True, upload_to='article_images/'),
        ),
    ]
