# Generated by Django 3.2.7 on 2022-07-07 01:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_article_aricle_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topik',
            fields=[
                ('top', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('id_top', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='topik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.topik'),
        ),
    ]
