# Generated by Django 3.2.7 on 2022-07-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0002_alter_dokumen_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumen',
            name='cover',
            field=models.ImageField(blank=True, default='dokumen/cover-default.png', null=True, upload_to='dokumen_cover/'),
        ),
        migrations.AddField(
            model_name='dokumen',
            name='tahun',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
