# Generated by Django 3.2.7 on 2022-07-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0005_auto_20220704_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='background_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kategori',
            name='icon',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
